version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9002:9000"       # API 端口
      - "9003:9001"       # 管理界面端口
    volumes:
      - ./data:/data      # 存储图片的物理路径
    environment:
      MINIO_ROOT_USER: "admin114514"          # 账号
      MINIO_ROOT_PASSWORD: "admin114514"  # 密码
    command: server /data --console-address ":9001"
    restart: always